# This workflow will build the Python project and publish the current tagged
# release to PyPI; it will only run if the triggering commit has been tagged
# For more information see:
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: publish

on:
  push:
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.13"

    - name: Check lockfile
      run: uv lock --check

    - name: Build a binary wheel and a source tarball
      run: uv build --sdist --wheel --out-dir dist/

    - name: Publish distribution to Test PyPI
      run: uv publish --publish-url https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      run: uv publish
